# Generated by Django 4.2.5 on 2023-12-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phoneno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='cardproduct',
            name='image',
            field=models.ImageField(upload_to='static/image/card/'),
        ),
    ]
