# Generated by Django 4.2.5 on 2023-12-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_alter_aboutus_options_alter_aboutus_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='body',
            field=models.CharField(max_length=1200),
        ),
    ]
