# Generated by Django 4.2.5 on 2023-12-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_alter_aboutus_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='body',
            field=models.TextField(),
        ),
    ]
